server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Concert
          uri: http://localhost:8081
          predicates:
            - Path=/concerts/** 
        - id: Booking
          uri: http://localhost:8082
          predicates:
            - Path=/bookings/** 
        - id: Alarm
          uri: http://localhost:8083
          predicates:
            - Path=/alarms/** 
        - id: Delivery
          uri: http://localhost:8084
          predicates:
            - Path=/deliveries/** 
        - id: Payment
          uri: http://localhost:8085
          predicates:
            - Path=/payments/** 
        - id: View
          uri: http://localhost:8086
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Concert
          uri: http://Concert:8080
          predicates:
            - Path=/concerts/** 
        - id: Booking
          uri: http://Booking:8080
          predicates:
            - Path=/bookings/** 
        - id: Alarm
          uri: http://Alarm:8080
          predicates:
            - Path=/alarms/** 
        - id: Delivery
          uri: http://Delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/payments/** 
        - id: View
          uri: http://View:8080
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080